In [2]:
import numpy as np
import pandas as pd

In [3]:
cctv = pd.read_csv('data/서울시 자치구 연도별 방범용 CCTV 운영 현황_230630기준.csv',encoding='EUC-KR', index_col='구분')
del cctv['Unnamed: 0']
cctv

      2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년   2023년
구분
종로구     935  1,066  1,225  1,322  1,338  1,526   1573   1812   1,808
중구      363    565    838  1,174  1,234  1,482   1911   2026   2,026
용산구   1,398  1,689  1,831  1,888  1,986  2,131   2321   2531   2,647
성동구   1,089  1,328  2,103  2,390  2,697  3,162   3519   3627   3,643
광진구     638    657  1,112  1,586  2,233  2,375   3111   3370   3,359
동대문구  1,202  1,425  1,535  1,775  1,969  2,142   2471   2592   2,592
중랑구     751    898  1,047  1,203  2,250  3,165   3592   3856   3,856
성북구   1,035  1,534  1,940  2,542  2,895  3,081   3815   4014   4,129
강북구     608    840    841  1,159  1,656  2,337   2960   3184   3,184
도봉구     345    443    542    679    835    979   1684   1994   2,120
노원구     956  1,268  1,433  1,577  1,763  2,021   2171   2284   2,281
은평구   1,719  2,075  2,310  2,669  3,164  3,431   3822   4103   4,103
서대문구    952  1,179  1,525  1,764  2,100  2,499   2591   2928   3,006
마포구     623    970  1,328  1,703  2,011  2,268   2372   2500   2,500
양천구   1,898  2,026  2,367  2,655  2,928  3,136   3393   3627   3,609
강서구     801    960  1,164  1,386  1,858  2,346   2637   3151   3,209
구로구   1,407  1,719  2,231  2,819  3,074  3,455   3842   4013   4,122
금천구     990  1,090  1,181  1,563  1,894  2,247   2276   2498   2,730
영등포구    904  1,140  1,429  2,055  2,093  3,250   3508   3896   3,964
동작구     961  1,200  1,471  1,690  1,904  2,155   2181   2404   2,402
관악구   1,496  2,048  2,611  3,247  3,800  4,071   3390   4029   4,245
서초구   1,548  1,785  2,169  2,582  2,938  3,175   3442   3180  3,180
강남구   2,319  3,447  4,232  4,834  5,459  5,796   6143   6495   6,495
송파구     713    798    913  1,364  2,052  2,372   2520   2805   2,821
강동구     670    863  1,134  1,596  1,871  2,475   2720   3086   3,088

In [5]:
for col in cctv.columns:
    print(col, type(cctv[col][0]))      # cctv 의 첫번째 행의 값의 데이터 타입 확인.

2015년 <class 'str'>
2016년 <class 'str'>
2017년 <class 'str'>
2018년 <class 'str'>
2019년 <class 'str'>
2020년 <class 'str'>
2021년 <class 'numpy.int64'>
2022년 <class 'numpy.int64'>
2023년 <class 'str'>

In [18]:
for col in cctv.columns:
    if col in ['2021년', '2022년']:
        continue
    cctv[col] = cctv[col].replace(',', '').astype(int)

In [16]:
cctv['계'] = cctv.sum(axis=1)
cctv.tail()

     2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년  2023년      계
구분
관악구   1496   2048   2611   3247   3800   4071   3390   4029   4245  57874
서초구   1548   1785   2169   2582   2938   3175   3442   3180   3180  47998
강남구   2319   3447   4232   4834   5459   5796   6143   6495   6495  90440
송파구    713    798    913   1364   2052   2372   2520   2805   2821  32716
강동구    670    863   1134   1596   1871   2475   2720   3086   3088  35006

In [4]:
cctv.dtypes

2015년    object
2016년    object
2017년    object
2018년    object
2019년    object
2020년    object
2021년     int64
2022년     int64
2023년    object
dtype: object

In [90]:
cctv.astype('string')

      구분  2015년  2016년  2017년  2018년  2019년  2020년 2021년 2022년   2023년
1    종로구    935  1,066  1,225  1,322  1,338  1,526  1573  1812   1,808
2     중구    363    565    838  1,174  1,234  1,482  1911  2026   2,026
3    용산구  1,398  1,689  1,831  1,888  1,986  2,131  2321  2531   2,647
4    성동구  1,089  1,328  2,103  2,390  2,697  3,162  3519  3627   3,643
5    광진구    638    657  1,112  1,586  2,233  2,375  3111  3370   3,359
6   동대문구  1,202  1,425  1,535  1,775  1,969  2,142  2471  2592   2,592
7    중랑구    751    898  1,047  1,203  2,250  3,165  3592  3856   3,856
8    성북구  1,035  1,534  1,940  2,542  2,895  3,081  3815  4014   4,129
9    강북구    608    840    841  1,159  1,656  2,337  2960  3184   3,184
10   도봉구    345    443    542    679    835    979  1684  1994   2,120
11   노원구    956  1,268  1,433  1,577  1,763  2,021  2171  2284   2,281
12   은평구  1,719  2,075  2,310  2,669  3,164  3,431  3822  4103   4,103
13  서대문구    952  1,179  1,525  1,764  2,100  2,499  2591  2928   3,006
14   마포구    623    970  1,328  1,703  2,011  2,268  2372  2500   2,500
15   양천구  1,898  2,026  2,367  2,655  2,928  3,136  3393  3627   3,609
16   강서구    801    960  1,164  1,386  1,858  2,346  2637  3151   3,209
17   구로구  1,407  1,719  2,231  2,819  3,074  3,455  3842  4013   4,122
18   금천구    990  1,090  1,181  1,563  1,894  2,247  2276  2498   2,730
19  영등포구    904  1,140  1,429  2,055  2,093  3,250  3508  3896   3,964
20   동작구    961  1,200  1,471  1,690  1,904  2,155  2181  2404   2,402
21   관악구  1,496  2,048  2,611  3,247  3,800  4,071  3390  4029   4,245
22   서초구  1,548  1,785  2,169  2,582  2,938  3,175  3442  3180  3,180
23   강남구  2,319  3,447  4,232  4,834  5,459  5,796  6143  6495   6,495
24   송파구    713    798    913  1,364  2,052  2,372  2520  2805   2,821
25   강동구    670    863  1,134  1,596  1,871  2,475  2720  3086   3,088

In [11]:
# 천단위 구분기호 옵션을 설정하면 쉽게 읽을 수 있음 
cctv = pd.read_csv('data/서울시 자치구 연도별 방범용 CCTV 운영 현황_230630기준.csv',
                   encoding='EUC-KR', index_col='구분', thousands=',')
del cctv['Unnamed: 0']
cctv

      2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년  2023년
구분
종로구     935   1066   1225   1322   1338   1526   1573   1812   1808
중구      363    565    838   1174   1234   1482   1911   2026   2026
용산구    1398   1689   1831   1888   1986   2131   2321   2531   2647
성동구    1089   1328   2103   2390   2697   3162   3519   3627   3643
광진구     638    657   1112   1586   2233   2375   3111   3370   3359
동대문구   1202   1425   1535   1775   1969   2142   2471   2592   2592
중랑구     751    898   1047   1203   2250   3165   3592   3856   3856
성북구    1035   1534   1940   2542   2895   3081   3815   4014   4129
강북구     608    840    841   1159   1656   2337   2960   3184   3184
도봉구     345    443    542    679    835    979   1684   1994   2120
노원구     956   1268   1433   1577   1763   2021   2171   2284   2281
은평구    1719   2075   2310   2669   3164   3431   3822   4103   4103
서대문구    952   1179   1525   1764   2100   2499   2591   2928   3006
마포구     623    970   1328   1703   2011   2268   2372   2500   2500
양천구    1898   2026   2367   2655   2928   3136   3393   3627   3609
강서구     801    960   1164   1386   1858   2346   2637   3151   3209
구로구    1407   1719   2231   2819   3074   3455   3842   4013   4122
금천구     990   1090   1181   1563   1894   2247   2276   2498   2730
영등포구    904   1140   1429   2055   2093   3250   3508   3896   3964
동작구     961   1200   1471   1690   1904   2155   2181   2404   2402
관악구    1496   2048   2611   3247   3800   4071   3390   4029   4245
서초구    1548   1785   2169   2582   2938   3175   3442   3180   3180
강남구    2319   3447   4232   4834   5459   5796   6143   6495   6495
송파구     713    798    913   1364   2052   2372   2520   2805   2821
강동구     670    863   1134   1596   1871   2475   2720   3086   3088